// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PesquisaWhatsApi.Data;

#nullable disable

namespace PesquisaWhatsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611184236_criarestruturainicial")]
    partial class criarestruturainicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PesquisaWhatsApi.Models.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Doenca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EsquecimentoRemedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequenciaTecnologia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenciaAbordagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsoApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
