// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PesquisaWhatsApi.Data;

#nullable disable

namespace PesquisaWhatsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PesquisaWhatsApi.Models.Conversa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataUltimaInteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("boolean");

                    b.Property<int?>("FluxoId")
                        .HasColumnType("integer");

                    b.Property<int?>("FluxoMensagemAtualId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.HasIndex("FluxoMensagemAtualId");

                    b.HasIndex("TelefoneUsuario", "Canal");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.FluxoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhInicio")
                        .HasColumnType("boolean");

                    b.Property<int>("FluxoId")
                        .HasColumnType("integer");

                    b.Property<int>("MensagemId")
                        .HasColumnType("integer");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProximaFluxoMensagemId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.HasIndex("MensagemId");

                    b.HasIndex("ProximaFluxoMensagemId");

                    b.ToTable("FluxoMensagens");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Fluxos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhPadrao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EhPadrao")
                        .IsUnique()
                        .HasFilter("\"EhPadrao\" = true");

                    b.ToTable("Fluxos");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.HistoricoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("HistoricoMensagens");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FluxoMensagemAtualId")
                        .HasColumnType("integer");

                    b.Property<string>("PalavraChave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProximaFluxoMensagemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FluxoMensagemAtualId");

                    b.HasIndex("ProximaFluxoMensagemId");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Conversa", b =>
                {
                    b.HasOne("PesquisaWhatsApi.Models.Fluxos", "Fluxo")
                        .WithMany()
                        .HasForeignKey("FluxoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PesquisaWhatsApi.Models.FluxoMensagem", "FluxoMensagemAtual")
                        .WithMany()
                        .HasForeignKey("FluxoMensagemAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fluxo");

                    b.Navigation("FluxoMensagemAtual");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.FluxoMensagem", b =>
                {
                    b.HasOne("PesquisaWhatsApi.Models.Fluxos", "Fluxo")
                        .WithMany("FluxoMensagens")
                        .HasForeignKey("FluxoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaWhatsApi.Models.Mensagem", "Mensagem")
                        .WithMany("FluxoMensagens")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaWhatsApi.Models.FluxoMensagem", "ProximaFluxoMensagem")
                        .WithMany()
                        .HasForeignKey("ProximaFluxoMensagemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fluxo");

                    b.Navigation("Mensagem");

                    b.Navigation("ProximaFluxoMensagem");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.HistoricoMensagem", b =>
                {
                    b.HasOne("PesquisaWhatsApi.Models.Conversa", "Conversa")
                        .WithMany("Historico")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Resposta", b =>
                {
                    b.HasOne("PesquisaWhatsApi.Models.FluxoMensagem", "FluxoMensagemAtual")
                        .WithMany("OpcoesRespostas")
                        .HasForeignKey("FluxoMensagemAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaWhatsApi.Models.FluxoMensagem", "ProximaFluxoMensagem")
                        .WithMany()
                        .HasForeignKey("ProximaFluxoMensagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FluxoMensagemAtual");

                    b.Navigation("ProximaFluxoMensagem");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Conversa", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.FluxoMensagem", b =>
                {
                    b.Navigation("OpcoesRespostas");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Fluxos", b =>
                {
                    b.Navigation("FluxoMensagens");
                });

            modelBuilder.Entity("PesquisaWhatsApi.Models.Mensagem", b =>
                {
                    b.Navigation("FluxoMensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
